```{r}
rm(list = ls())
dir.save <- getwd()
set.seed(1232)

setwd("C:/Users/Gabriel/Documents/Gabriel/IC/HGP-INLA/")

# source("blockNNGPfunctionREGULAR.R")
# source("blockNNGPfunctionIRREGULAR.R")
source("NNGPfunction.R")
source("blockNNGPrgeneric.R")
source("NNGPrgeneric.R")
source("Irregblock.R")
source("utils.R")

library(INLA)
library(fields)
library(lattice)
library(akima)
library(Matrix)
library(slam)
library(igraph)
library(coda)
library(MBA)
library(mvtnorm)
library(ggforce)
library(Rcpp)
library(tidyverse)
library(raster)
library(sf)
```

```{r} set spatial parameters
sigma.sq <- 1
tau.sq <- 0.1
phi <- 1 / 3
alpha <- 1
```

```{r}
# #  generate point data
# n <- 200
# loc <- cbind(runif(n, 0, 1), runif(n, 0, 1))
# colnames(loc) <- c("x", "y")

# sf <- st_as_sf(
#   as.data.frame(loc),
#   coords = c("x", "y"),
#   crs = 4326
# )

# #  pass spatial parameters

# range <- log(10)^(1 / alpha) * phi  # aonde é usado?

# # distMatrix <- as.matrix(dist(loc))

# R <- exp((-1) * (distMatrix / phi)^alpha)
# diag(R) <- 1
# nloc <- dim(loc)[1]
# C <- sigma.sq * R

# D <- chol(C)
# rnorm_n.obs <- rnorm(n)
# w <- t(matrix(rnorm_n.obs, ncol = (n)) %*% D)

# X <- as.matrix(cbind(1, rnorm(nloc))) ## X = intercept + covariate

# B <- as.matrix(c(1, 5))
# p <- length(B)

# y <- rnorm(nloc, X %*% B + w, sqrt(tau.sq)) ## y= X beta + w(spatial) + nugget

```

```{r}

library(CARBayesdata)
data(GGHB.IZ)
data(respiratorydata) # dados usados pelo Lucas

sf <- GGHB.IZ[GGHB.IZ$IZ %in% respiratorydata$IZ, ]["geometry"]
loc <- st_coordinates(st_centroid(sf))
n <- nrow(loc)

y <- respiratorydata$observed
X <- as.matrix(cbind(1, respiratorydata$incomedep)) ## X = intercept + covariate
E <- respiratorydata$expected # offset

# y ~ pois(μi)
# log(μ_i​) = log(E_i​) + β_0 ​+ β_1 * ​incomedep_i ​+ f_i​

```


```{r}
# retrieve model
n.partition <- 8
n.blocks <- n.partition^2
num.nb <- 2

HGPdata <- get_HGPdata(loc, sf, n.blocks, num.nb) # blocks é definido dentro de get_HGPdata
```


```{r}
### %%%%%%%%%%%%%%%%%%%%%%% END  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

## run model with INLA

# response variable and covariates FOR POINT DATA
data1 <- data.frame(y = y, x = X[, 2])
data1$idx <- 1:nrow(data1)

## set the blockNNGP as latent effect
# formula to fit the blockNNGP model
# f() ensure that the latent effect is the blockNNGP
f.blockNNGP <- y ~ 1 + x + f(idx, model = HGPdata$model)

# inla function to fit the model
# The user can change the family and priors here.
resf <- inla(
  f.blockNNGP,
  data = as.data.frame(data1),
  family = "poisson",
  E = E
)

print(names(resf$marginals.hyperpar))

# Recovering the posterior mean estimation of nugget, marginal variance and phi parameters.
tau.est <- inla.emarginal(function(x) 1 / x, resf$marginals.hyperpar[[1]])
sigmasq.est <- inla.emarginal(
  function(x) exp(-x),
  resf$marginals.hyperpar[[2]]
)
# phi.est <- inla.emarginal(
#   function(x) 1 - 1 / (1 + exp(x)),
#   resf$marginals.hyperpar[[3]]
# )
# summary.theta <- c(tau.est, sigmasq.est, phi.est)
# print(c("tau.est", "sigmasq.est", "phi.est"))

## posterior mean of spatial random effects
est.w <- resf$summary.random$idx$mean
summary.theta <- c(tau.est, sigmasq.est)
print(c("tau.est", "sigmasq.est")) # supposed to be sigmasq.est and rho.est?

print(summary.theta)


print(resf)
# return(resf)
```