```{r} INIT
# rm(list = ls())
set.seed(1232)

source("blockNNGPfunctionREGULAR.R")
source("blockNNGPfunctionIRREGULAR.R")
source("NNGPfunction.R")
source("blockNNGPrgeneric.R")
source("NNGPrgeneric.R")
source("Irregblock.R")
source("utils.R")

library(INLA)
library(fields)
library(lattice)
library(akima)
library(Matrix)
library(slam)
library(igraph)
library(coda)
library(MBA)
library(mvtnorm)
library(ggforce)
library(Rcpp)
library(tidyverse)
library(raster)
library(sf)
```

```{r} Generate point data
n <- 200
loc <- cbind(runif(n, 0, 1), runif(n, 0, 1))
colnames(loc) <- c("x", "y")

sf <- st_as_sf(
  as.data.frame(loc),
  coords = c("x", "y"),
  crs = 4326
)

#  pass spatial parameters
sigma.sq <- 1
tau.sq <- 0.1
phi <- 1 / 3
alpha <- 1

range <- log(10)^(1 / alpha) * phi

distMatrix <- as.matrix(dist(loc))
R <- exp((-1) * (distMatrix / phi)^alpha)


diag(R) <- 1
nloc <- dim(loc)[1]
C <- sigma.sq * R

D <- chol(C)
rnorm_n.obs <- rnorm(n)
w <- t(matrix(rnorm_n.obs, ncol = (n)) %*% D)

X <- as.matrix(cbind(1, rnorm(nloc))) ## X = intercept + covariate

B <- as.matrix(c(1, 5))
p <- length(B)

y <- rnorm(nloc, X %*% B + w, sqrt(tau.sq)) ## y= X beta + w(spatial) + nugget

```


```{r} Generate HGP model
n.partition <- 8
n.blocks <- n.partition^2
num.nb <- 2
HGPdata <- get_HGPdata(loc, sf, y, X, n.blocks, num.nb, isPointData = TRUE)

nb <- HGPdata$nb
ind_obs1 <- HGPdata$ind_obs1
indb <- HGPdata$indb
coords.D <- HGPdata$coords.D
```

```{r} Run model with INLA
blockNNGP.model <- HGPdata$model

data1 <- data.frame(y = y, x = X[, 2])
data1$idx <- 1:nrow(data1)

f.blockNNGP <- y ~ 1 + x + f(idx, model = blockNNGP.model)
resf <- inla(f.blockNNGP, data = as.data.frame(data1), family = "gaussian")

# Extraction of hyperparameters
tau.est <- inla.emarginal(function(x) 1 / x, resf$marginals.hyperpar[[1]])
sigmasq.est <- inla.emarginal(function(x) exp(-x), resf$marginals.hyperpar[[2]])
phi.est <- inla.emarginal(
  function(x) 1 - 1 / (1 + exp(x)),
  resf$marginals.hyperpar[[3]]
)
w.est <- resf$summary.random$idx$mean

summary.theta <- c(tau.est, sigmasq.est, phi.est)
print(c("tau.est", "sigmasq.est", "phi.est"))
print(summary.theta)
```
