```{r} INIT
rm(list = ls())
#set.seed(1232)

source("blockNNGPrgeneric.R")
source("Irregblock.R")
source("utils.R")

library(INLA)
library(mvtnorm)
library(tidyverse)
library(sf)

# dados usados pelo Lucas
library(CARBayesdata)
data(GGHB.IZ)
data(respiratorydata)
```

```{r} Get aereal mixed data and extract features
sf <- GGHB.IZ[GGHB.IZ$IZ %in% respiratorydata$IZ, ]["geometry"]
n <- nrow(sf)

y <- respiratorydata$observed
X <- as.matrix(cbind(1, scale(respiratorydata$incomedep))) ## X = intercept + covariate
E <- respiratorydata$expected # offset
```


```{r} Generate HGP model
n.partition <- 4
n.blocks <- n.partition^2
num.nb <- 2

HGPdata <- get_HGPdata(
  sf,
  y,
  X,
  n.blocks,
  num.nb
)

y <- y[(HGPdata$order)]
X <- X[(HGPdata$order), ]
E <- E[(HGPdata$order)]
blockNNGP.model <- HGPdata$model
```

```{r} Run model with INLA'
M <- 30
out <- matrix(0, ncol = 5, nrow = M)

data1 <- data.frame(y = y, x = X[, 2])
data1$idx <- 1:nrow(data1)

f.blockNNGP <- y ~ 1 + x + f(idx, model = blockNNGP.model)

for (i in 1:M) {
  set.seed(i)
  print(i)

  resf <- inla(
    f.blockNNGP,
    data = as.data.frame(data1),
    family = "poisson",
    E = E
  )

  summary(resf)

  # Theta1 = (log(1/σ²))  ! supposed to be sigma not sigmasq?
  sigmasq.est <- inla.emarginal(
    function(x) exp(-x),
    resf$marginals.hyperpar[[1]]
  )

  # Theta3 = logit(phi)
  nu.est <- inla.emarginal(
    function(x) plogis(x),
    resf$marginals.hyperpar[[3]]
  )

  # Theta2 = logit(ϕ) -> rho = log(10)^1/ν * φ
  rho.est <- inla.emarginal(
    function(x) log(10)^(1 / (nu.est)) * (10 - (10) / (1 + exp(x))),
    resf$marginals.hyperpar[[2]]
  )

  # rho.est <- log(10)^(1 / (0.7)) * phi.est
  # rho.est <- log(10)^(1 / (alpha)) * phi.est

  # Resultado transformado
  cat("σ²:", sigmasq.est, "\n") # deve ser 0.19
  cat("ϕ :", rho.est, "\n") # deve ser 2.25
  cat("ν :", nu.est, "\n") # deve ser 2.25

  # print(resf)
  out[i, ] <- c(resf$summary.fixed[, 1], sigmasq.est, rho.est, nu.est)
}
```
