```{r}
rm(list=ls())
source("blockNNGPfunctionREGULAR.R")
source("blockNNGPfunctionIRREGULAR.R")
source("NNGPfunction.R")
source("blockNNGPrgeneric.R")
source("NNGPrgeneric.R")
source("Irregblock.R")
source("utils.R")

#######################
## libraries required
####################### 
library(INLA)
library(fields)
library(lattice)
library(akima) 
library(Matrix)
library(slam)
library(igraph)
library(coda)
library(MBA)
library(mvtnorm)
library(ggforce)
library(Rcpp)
library(tidyverse)
library(raster)


dir.save = getwd()


## simulate data
n 	<- 2500




loc 	<- cbind(runif(n,0,1), runif(n,0,1))


##Matern##
sigma.sq <- 1
tau.sq	 <- 0.1
nu 	 <- 0.5
phi 	 <- 3

range    <- sqrt(8 * nu) / phi
D 	 <- as.matrix(dist(loc))
R 	 <- (D*phi)^nu/(2^(nu-1)*gamma(nu))*besselK(x=D*phi, nu=nu)
diag(R)  <- 1


nloc 	 <- dim(loc)[1]

C 	 <- sigma.sq*R

D 	 	<- chol(C)
rnorm_n.obs 	<- rnorm(n)
w 		<- t(matrix(rnorm_n.obs, ncol=(n))%*%D )

X 		<- as.matrix(cbind(1, rnorm(nloc))) ## X = intercept + covariate

B 		<- as.matrix(c(1,5))
p 		<- length(B)

y 		<- rnorm(nloc, X%*%B + w, sqrt(tau.sq)) ## y= X beta + w(spatial) + nugget
```

```{r run-INLA}
case='irregular'


#number of blocks (nexp=7 ---> n.blocks=2^7)
nexp 	 <- 7
n.blocks <- 2^nexp
#number of neigbhor blocks
num.nb   <- 2
res2	 <- blockNNGP(case, loc,  y, X, w, dir.save, n.blocks, num.nb)
#summary(res2)

#number of blocks (nexp=6 ---> n.blocks=2^6)
nexp 	 <- 6
n.blocks <- 2^nexp
#number of neigbhor blocks
num.nb   <- 2
res3 	 <- blockNNGP(case, loc,  y, X, w,  dir.save, n.blocks, num.nb)

```