```{r}
rm(list = ls())
dir.save = getwd()

source("blockNNGPrgeneric.R")
source("Irregblock.R")
source("utils.R")

library(INLA)
library(mvtnorm)
library(tidyverse)
library(sf)
library(units)
```

```{r} set spatial parameters
sigma.sq <- .20
rho <- 8
alpha <- 0.75
phi <- rho/(log(10)^(1/alpha))
```

```{r}
library(CARBayesdata)
data(GGHB.IZ)
data(respiratorydata) # dados usados pelo Lucas

sf <- GGHB.IZ[GGHB.IZ$IZ %in% respiratorydata$IZ, ]["geometry"]
n = nrow(sf)

distMatrix <- st_distance(sf, which = "Hausdorff") |>
                units::set_units(value = "km") |>
                units::set_units(value = NULL) |>
                as.matrix()

R <- exp((-1) * (distMatrix / phi)^alpha)
diag(R) <- 1
C <- sigma.sq * R

D <- chol(C)
#set.seed(1232)

B <- as.matrix(c(-0.2, 0.35))
p <- length(B)

X <- as.matrix(cbind(1, respiratorydata$incomedep/100)) ## X = intercept + covariate
E = respiratorydata$expected  # offset
eta <- X %*% B
```


```{r} Generate HGP model
n.partition <- 4
n.blocks <- n.partition^2
num.nb <- 2

HGPdata <- get_HGPdata(
  sf,
  y,
  X,
  n.blocks,
  num.nb,
  alpha = alpha
)

blockNNGP.model <- HGPdata$model
```
```{r} Run model with INLA'
M <- 100
out <- matrix(0,ncol=4,nrow=M)

Xnew <- X[(HGPdata$order), ]
Enew <- E[(HGPdata$order)]

for(i in 1:M){
set.seed(i)
print(i)
rnorm_n.obs <- rnorm(n)
w <- t(matrix(rnorm_n.obs, ncol = (n)) %*% D)

lambda = E*exp(eta + w)
#set.seed(102910)
y <- rpois(n, lambda)

y <- y[(HGPdata$order)]
data1 <- data.frame(y = y, x = Xnew[, 2])
data1$idx <- 1:nrow(data1)

f.blockNNGP <- y ~ 1 + x + f(idx, model = blockNNGP.model)

resf <- inla(
  f.blockNNGP,
  data = as.data.frame(data1),
  family = "poisson",
  E = Enew
)

#summary(resf)

# Theta1 = (log(1/σ²))  ! supposed to be sigma not sigmasq?
sigmasq.est <- inla.emarginal(
  function(x) exp(-x),
  resf$marginals.hyperpar[[1]]
)

# Theta2 = logit(ϕ) -> rho = log(10)^1/ν * φ
rho.est <- inla.emarginal(
  function(x) log(10)^(1 / (alpha)) * (10 - 10 / (1 + exp(x))),
  resf$marginals.hyperpar[[2]]
)

# rho.est <- log(10)^(1 / (0.7)) * phi.est
# rho.est <- log(10)^(1 / (alpha)) * phi.est

# Resultado transformado
#cat("σ²:", sigmasq.est, "\n") # deve ser 0.19
#cat("ϕ :", rho.est, "\n") # deve ser 2.25

out[i,] <- c(resf$summary.fixed[,1],sigmasq.est,rho.est)
}
```


```{r} Analyze output'
apply(out,2,summary)
boxplot(out)
```
