```{r} INIT
rm(list = ls())
#set.seed(1232)

source("blockNNGPrgeneric.R")
source("Irregblock.R")
source("utils.R")

library(INLA)
library(mvtnorm)
library(tidyverse)
library(sf)

# dados usados pelo Lucas
library(CARBayesdata)
data(GGHB.IZ)
data(respiratorydata)
```

```{r} Get aereal mixed data and extract features
sf <- GGHB.IZ[GGHB.IZ$IZ %in% respiratorydata$IZ, ]["geometry"]
n <- nrow(sf)

y <- respiratorydata$observed
X <- as.matrix(cbind(1, scale(respiratorydata$incomedep))) ## X = intercept + covariate
E <- respiratorydata$expected # offset
```


```{r} Generate HGP model
n.partition <- 4
n.blocks <- n.partition^2
num.nb <- 2

alpha <- 0.7

HGPdata <- get_HGPdata(
  sf,
  y,
  X,
  n.blocks,
  num.nb,
  alpha = alpha
)

y <- y[(HGPdata$order)]
X <- X[(HGPdata$order), ]
E <- E[(HGPdata$order)]
blockNNGP.model <- HGPdata$model
```

```{r} Run model with INLA'
data1 <- data.frame(y = y, x = X[, 2])
data1$idx <- 1:nrow(data1)

f.blockNNGP <- y ~ 1 + x + f(idx, model = blockNNGP.model)

resf <- inla(
  f.blockNNGP,
  data = as.data.frame(data1),
  family = "poisson",
  E = E
)

summary(resf)

# Theta1 = (log(1/σ²))  ! supposed to be sigma not sigmasq?
sigmasq.est <- inla.emarginal(
  function(x) exp(-x),
  resf$marginals.hyperpar[[1]]
)

# Theta2 = logit(ϕ) -> rho = log(10)^1/ν * φ
rho.est <- inla.emarginal(
  function(x) log(10)^(1 / (alpha)) * (10 - (10) / (1 + exp(x))),
  resf$marginals.hyperpar[[2]]
)

# rho.est <- log(10)^(1 / (0.7)) * phi.est
# rho.est <- log(10)^(1 / (alpha)) * phi.est

# Resultado transformado
cat("σ²:", sigmasq.est, "\n") # deve ser 0.19
cat("ϕ :", rho.est, "\n") # deve ser 2.25


print(resf)
```
