```{r} INIT
rm(list = ls())
set.seed(1232)
setwd(
  "C:/Users/GabrielNascimento/Downloads/HGP-INLA-novo"
)

source("blockNNGPrgeneric.R")
source("utils.R")
library(tidyverse)
library(sf)
library(INLA)
```

```{r}
n <- 1000

#  pass spatial parameters
sigma.sq <- 1
tau.sq <- 0.1
phi <- 1 / 3
alpha <- 1
B <- as.matrix(c(1, 5))

n.partition <- 8
n.blocks <- n.partition^2
num.nb <- 2
priors = list(a = 0, b = 2.432049)
```

```{r} Generate point data
loc <- cbind(runif(n, 0, 1), runif(n, 0, 1))
colnames(loc) <- c("x", "y")

sf <- st_as_sf(
  as.data.frame(loc),
  coords = c("x", "y"),
  crs = 4326
)
distMatrix <- as.matrix(dist(loc))
nloc <- n
n <- nrow(sf)

rnorm_n.obs <- rnorm(n)

range <- log(10)^(1 / alpha) * phi
R <- exp((-1) * (distMatrix / phi)^alpha)
diag(R) <- 1
C <- sigma.sq * R
D <- chol(C)


w <- t(matrix(rnorm_n.obs, ncol = (n)) %*% D)
p <- length(B)
X <- as.matrix(cbind(1, rnorm(nloc))) ## X = intercept + covariate
y <- rnorm(nloc, X %*% B + w, sqrt(tau.sq)) ## y= X beta + w(spatial) + nugget
```


```{r} Generate HGP model
HGPdata <- get_HGPdata(sf, n.blocks, num.nb, alpha, priors)

blockNNGP.model <- HGPdata$model
order = HGPdata$order
Xnew = X[order, ]
ynew = y[order]
```

```{r} Run model with INLA
data1 <- data.frame(y = ynew, x = Xnew[, 2])
data1$idx <- 1:nrow(data1)

f.blockNNGP <- y ~ 1 + x + f(idx, model = blockNNGP.model)
resf <- inla(f.blockNNGP, data = as.data.frame(data1), family = "gaussian")

# Extraction of hyperparameters
tau.est <- inla.emarginal(function(x) 1 / x, resf$marginals.hyperpar[[1]])
sigmasq.est <- inla.emarginal(function(x) exp(-x), resf$marginals.hyperpar[[2]])
phi.est <- inla.emarginal(
  function(x) 1 - 1 / (1 + exp(x)),
  resf$marginals.hyperpar[[3]]
)
w.est <- resf$summary.random$idx$mean

summary.theta <- c(tau.est, sigmasq.est, phi.est)
print(c("tau.est", "sigmasq.est", "phi.est"))
print(resf$summary.fixed)
print(summary.theta)
```
