--- PARÂMETROS ESTIMADOS DO MODELO ---

Efeitos Fixos (β):
                  mean 0.025quant 0.975quant
(Intercept) -0.2196752 -0.2576255 -0.1821968
x            0.3313440  0.2936071  0.3694941

Hiperparâmetros do Efeito Espacial (Estimativas Pontuais):
  - Variância Espacial (σ²): 0.0345
  - Alcance Prático (ρ):    1.6459

--- CRITÉRIOS DE AJUSTE DO MODELO (Goodness of Fit) ---

DIC:   1050.24
WAIC:  1039.32
LOOIC: NA
---------------------------------------------------

```{r} INIT
rm(list = ls())

source("blockNNGPrgeneric.R")
source("Irregblock.R")
source("utils.R")

library(INLA)
library(tidyverse)
require(Matrix)
library(sf)

# dados usados pelo Lucas
library(CARBayesdata)
data(GGHB.IZ)
data(respiratorydata)
```


```{r}
n.partition <- 4
n.blocks <- 2^n.partition
num.nb <- 2

alpha <- 0.7
M = 3
```


```{r} Get aereal mixed data and extract features
sf <- GGHB.IZ[GGHB.IZ$IZ %in% respiratorydata$IZ, ]["geometry"]
n <- nrow(sf)

y <- respiratorydata$observed

m = bind_cols(sf, y)
plot(m)
X <- as.matrix(cbind(1, scale(respiratorydata$incomedep))) ## X = intercept + covariate
E <- respiratorydata$expected # offset
```


```{r} Generate HGP model
priors = list(a = 0, b = max(st_distance(sf) / 2))

HGPdata <- get_HGPdata(sf, n.blocks, num.nb, alpha, priors)

y <- y[(HGPdata$order)]
X <- X[(HGPdata$order), ]
E <- E[(HGPdata$order)]
blockNNGP.model <- HGPdata$model
```


```{r} Run model with INLA
# 1. Preparar os dados para o INLA
# ----------------------------------------------------
data1 <- data.frame(y = y, x = X[, 2])
data1$idx <- 1:nrow(data1)
f.blockNNGP <- y ~ 1 + x + f(idx, model = blockNNGP.model)

# ----------------------------------------------------
resf <- inla(
  f.blockNNGP,
  data = as.data.frame(data1),
  family = "poisson",
  E = E,
  control.compute = list(dic = TRUE, waic = TRUE, cpo = TRUE)
)

```




```{r}
# --- Código Básico usando inla.qmarginal ---

# Efeitos Fixos (Betas)
beta0_interval <- inla.qmarginal(
  c(0.025, 0.975),
  resf$marginals.fixed[["(Intercept)"]]
)
beta1_interval <- inla.qmarginal(c(0.025, 0.975), resf$marginals.fixed[["x"]])

# Alcance Prático (rho)
rho_interval <- inla.qmarginal(
  c(0.025, 0.975),
  resf$marginals.hyperpar[1]
)

# Variância Espacial (sigma^2)
sigma_marginal <- resf$marginals.hyperpar[2]
sigma_sq_marginal <- inla.tmarginal(
  fun = function(x) x^2,
  marginal = sigma_marginal
)
sigma_sq_interval <- inla.qmarginal(c(0.025, 0.975), sigma_sq_marginal)

# --- Exibir Resultados ---
print("Intervalo para Intercepto (beta_0):")
print(beta0_interval)

print("Intervalo para Coeficiente (beta_1):")
print(beta1_interval)

print("Intervalo para Alcance Prático (rho):")
print(rho_interval)

print("Intervalo para Variância Espacial (sigma^2):")
print(sigma_sq_interval)
```